DROP TABLE if EXISTS usertbl;
CREATE TABLE usertbl(
userID CHAR(8) NOT NULL,
userName VARCHAR(10) NOT NULL,
birthYear INT NOT NULL,
CONSTRAINT PRIMARY KEY PK_userTBL_userID (userID)
);

ALTER TABLE usertbl
ADD CONSTRAINT PK_userTBL_userID
PRIMARY KEY (userID);

CREATE TABLE buytbl(
num INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
userID CHAR(8) NOT NULL,
prodName CHAR(6) NOT NULL,
FOREIGN KEY (userID) REFERENCES usertbl (userID)
);

DROP TABLE if EXISTS buytbl;
CREATE TABLE buytbl(
num INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
userID CHAR(8) NOT NULL,
prodName CHAR(6) NOT NULL,
CONSTRAINT FK_userTBL_buyTBL FOREIGN KEY (userID) REFERENCES usertbl(userID)
);

DROP TABLE if EXISTS buytbl;
CREATE TABLE buytbl(
num INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
userID CHAR(8) NOT NULL,
prodName CHAR(6) NOT null
);

ALTER TABLE buytbl ADD CONSTRAINT FK_userTBL_buyTBL FOREIGN KEY (userID) REFERENCES usertbl(userID);

SHOW INDEX FROM buytbl;
ALTER TABLE buytbl DROP FOREIGN KEY FK_userTBL_buyTBL;

ALTER TABLE buytbl ADD CONSTRAINT FK_userTBL_buyTBL FOREIGN KEY (userID) REFERENCES usertbl (userID) ON UPDATE CASCADE;

USE tabledb;
DROP TABLE if EXISTS buytbl, usertbl;
CREATE TABLE usertbl(
userID CHAR(8) NOT NULL PRIMARY KEY,
userName VARCHAR(10) NOT NULL,
birthYear INT NOT NULL,
email CHAR(30) NULL,
);

DROP TABLE if EXISTS usertbl;
CREATE TABLE usertbl(
userID CHAR(8) NOT NULL PRIMARY KEY,
userName VARCHAR(10) NOT NULL,
birthYear INT NOT NULL,
email CHAR(30) NULL,
CONSTRAINT AK_email UNIQUE (email)
);

DROP TABLE if EXISTS usertbl;
CREATE TABLE usertbl(
userID CHAR(8) PRIMARY KEY,
userName VARCHAR(10),
birthYear INT CHECK (birthYear >= 1900 AND birthYear <= 2020),
mobile1 CHAR(3) NULL,
CONSTRAINT CK_name CHECK (userName IS NOT null)
);

ALTER TABLE usertbl
ADD CONSTRAINT CK_mobile1
CHECK (mobile1 IN ('010','011','016','017','018','019')) ;

DROP TABLE if EXISTS usertbl;
CREATE TABLE usertbl(
userID CHAR(8) NOT NULL PRIMARY KEY,
userName VARCHAR(10) NOT NULL,
birthYear INT NOT NULL DEFAULT -1,
addr CHAR(2) NOT NULL DEFAULT '서울',
mobile1 CHAR(3) NULL,
mobile2 CHAR(8) NULL,
height SMALLINT NULL DEFAULT 170,
mDate DATE null
);

DROP TABLE if EXISTS usertbl;
CREATE TABLE usertbl(
userID CHAR(8) NOT NULL PRIMARY KEY,
userName VARCHAR(10) NOT NULL,
birthYear INT NOT NULL,
addr CHAR(2) NOT NULL,
mobile1 CHAR(3) NULL,
mobile2 CHAR(8) NULL,
height SMALLINT NULL,
mDate DATE null
);

ALTER TABLE usertbl
ALTER COLUMN birthYear SET DEFAULT -1;
ALTER TABLE usertbl
ALTER COLUMN addr SET DEFAULT '서울';
ALTER TABLE usertbl
ALTER COLUMN height SET DEFAULT 170;

INSERT INTO usertbl VALUES ('LHL','이혜리',DEFAULT,DEFAULT,'011','1234567',DEFAULT,'2022.12.12');
INSERT INTO usertbl (userID,userName) VALUES ('KAY','김아영');
INSERT INTO usertbl VALUES ('WB','원빈',1982,'대전','019','9876543',176,'2023.5.5');
SELECT * FROM usertbl;

